#!/bin/sh
# Install NPM dependencies to _sass directory and symlink to node_modules

set -e

npm install
rm -rf _sass/node_modules
mv node_modules _sass
ln -s _sass node_modules

# Normalize.css is distributed as CSS, which Sass dosen't like. Convert to scss.
if test -e "_sass/normalize.css/normalize.css"; then
  mv -f _sass/normalize.css/normalize.css _sass/normalize.css/normalize.scss
fi

# All of the primitives are CSS, which Sass doesn't like. Convert to scss.
for file in $(find _sass/@primer/primitives/dist/css -name "*.css"); do
  mv -f ${file} ${file%.css}.scss
done

# Add our own theme scss file for consistency of naming in `assets/style.scss`
content='
@import "@primer/primitives/dist/css/base/size/size.scss";
@import "@primer/primitives/dist/css/base/typography/typography.scss";
@import "@primer/primitives/dist/css/functional/size/border.scss";
@import "@primer/primitives/dist/css/functional/size/breakpoints.scss";
@import "@primer/primitives/dist/css/functional/size/size-coarse.scss";
@import "@primer/primitives/dist/css/functional/size/size-fine.scss";
@import "@primer/primitives/dist/css/functional/size/size.scss";
@import "@primer/primitives/dist/css/functional/size/viewport.scss";
@import "@primer/primitives/dist/css/functional/typography/typography.scss";

@import "@primer/css/color-modes/index.scss";
@import "@primer/css/support/index.scss";
@import "@primer/css/base/index.scss";
@import "@primer/css/utilities/index.scss";
@import "@primer/css/layout/index.scss";
@import "@primer/css/markdown/index.scss";
@import "@primer/css/buttons/index.scss";
@import "@primer/css/tooltips/index.scss";
[data-color-mode=light][data-light-theme*=light],
[data-color-mode=dark][data-dark-theme*=light] {
  @import "rouge-light.scss";
}
[data-color-mode=light][data-light-theme*=dark],
[data-color-mode=dark][data-dark-theme*=dark] {
  @import "rouge-dark.scss";
}
@media(prefers-color-scheme: light) {
  [data-color-mode=auto][data-light-theme*=light]{
    @import "rouge-light.scss";
  }
}
@media(prefers-color-scheme: dark) {
  [data-color-mode=auto][data-dark-theme*=dark]{
    @import "rouge-dark.scss";
  }
}
div.highlight {
  border-radius: 6px;
}
.markdown-body div.highlighter-rouge>div.highlight {
  display: flex;
  justify-content: space-between;
}

clipboard-copy {
    height: 28px;
    width: 28px;
}
'
echo "$content" > _sass/jekyll-v4-theme-primer.scss

# Create rouge stylesheet
rougify style github.light > _sass/rouge-light.scss
rougify style github.dark > _sass/rouge-dark.scss

# Copy @github/clipboard_copy_element into assets/js
cp _sass/node_modules/@github/clipboard-copy-element/dist/bundle.js assets/js/github-clipboard-copy-element.js
