#!/bin/sh
# Install NPM dependencies to _sass directory and symlink to node_modules

set -e

npm install
rm -rf _sass/node_modules
mv node_modules _sass
ln -s _sass node_modules

# Normalize.css is distributed as CSS, which Sass dosen't like. Convert to scss.
if test -e "_sass/normalize.css/normalize.css"; then
  mv -f _sass/normalize.css/normalize.css _sass/normalize.css/normalize.scss
fi

# Add our own theme scss file for consistency of naming in `assets/style.scss`
content='
@import "@primer/css/color-modes/index.scss";
@import "@primer/css/support/index.scss";
@import "@primer/css/base/index.scss";
@import "@primer/css/utilities/index.scss";
@import "@primer/css/layout/index.scss";
@import "@primer/css/markdown/index.scss";
[data-color-mode=light][data-light-theme*=light],
[data-color-mode=dark][data-dark-theme*=light] {
  @import "rouge-light.scss";
}
[data-color-mode=light][data-light-theme*=dark],
[data-color-mode=dark][data-dark-theme*=dark] {
  @import "rouge-dark.scss";
}
@media(prefers-color-scheme: light) {
  [data-color-mode=auto][data-light-theme*=light]{
    @import "rouge-light.scss";
  }
}
@media(prefers-color-scheme: dark) {
  [data-color-mode=auto][data-dark-theme*=dark]{
    @import "rouge-dark.scss";
  }
}
div.highlight {
  border-radius: 6px;
}
'
echo "$content" > _sass/jekyll-v4-theme-primer.scss

# Create rouge stylesheet
rougify style github.light > _sass/rouge-light.scss
rougify style github.dark > _sass/rouge-dark.scss
